site_name: 'Example with Animals'
site_description: An informative description
plugins:
  - techdocs-core
nav:
  - Overview: 'index.md'
  - What is a fish: 'fish.md'
  - All the Animals: 'animals/all.md'
  - Each Animal:
    - dog: 'animals/dog.md'
    - cat: 'animals/cat.md'
    - frog: 'animals/frog.md'
    - hamster: 'animals/hamster.md'
    - snake: 'animals/snake.md'
    - elephant: 'animals/elephant.md'
    - giraffe: 'animals/giraffe.md'